"""add Department

Revision ID: 95220b766ddd
Revises: de62dcdefbbd
Create Date: 2024-06-24 13:28:40.840067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95220b766ddd'
down_revision = 'de62dcdefbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
